Repository mvoemel/studyflow, pull requests merged in 2024-12, with the labels that each got.

#81 Feature/semesters
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/SemesterController.java
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/deo/SemesterDeo.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/curriculum/Semester.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/curriculum/SemesterManager.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/curriculum/imps/SemesterManagerImpl.java
  backend/app/src/main/java/ch/zhaw/studyflow/services/persistence/SemesterDao.java
  backend/app/src/main/java/ch/zhaw/studyflow/services/persistence/memory/InMemorySemesterDao.java
Labels: feature

#93 85 bug use degreesidgrades with defined body payload instead of modulesidgrades endpoint
  client/src/lib/api/degrees/update-grades-for-module.ts
  client/src/lib/api/index.ts
Labels: bug

#90 test created
  backend/app/src/test/java/ch/zhaw/studyflow/webserver/controllers/SimpleControllerRegistryBuilderTest.java
  backend/app/src/test/java/ch/zhaw/studyflow/webserver/controllers/routing/RestRouteTest.java
  backend/app/src/test/java/ch/zhaw/studyflow/webserver/controllers/routing/RouteTrieTest.java
  backend/app/src/test/java/ch/zhaw/studyflow/webserver/http/contents/JsonContentTest.java
  backend/app/src/test/java/ch/zhaw/studyflow/webserver/http/contents/MapReadableBodyContentFactoryTest.java
  backend/app/src/test/java/ch/zhaw/studyflow/webserver/http/contents/TextContentTest.java
  backend/app/src/test/java/ch/zhaw/studyflow/webserver/http/cookies/CookieTest.java
  backend/app/src/test/java/ch/zhaw/studyflow/webserver/http/pipeline/InvokeByRequestContextEndpointInvokerTest.java
  backend/app/src/test/java/ch/zhaw/studyflow/webserver/sun/SunHttpServerWebServerBuilderTest.java
  backend/app/src/test/java/ch/zhaw/studyflow/webserver/sun/SunHttpServerWebServerTest.java
Labels: feature

#94 Feature/grades modal
  client/src/components/dialogforms/add-grade-form.tsx
  client/src/components/dialogs/add-grade.tsx
  client/src/components/global/grades-view.tsx
Labels: feature

#82 Feature/degree
  backend/app/src/main/java/ch/zhaw/studyflow/Main.java
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/DegreeController.java
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/StudentController.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/curriculum/Degree.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/curriculum/DegreeManager.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/curriculum/impls/DegreeManagerImpl.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/curriculum/imps/DegreeManagerImpl.java
  backend/app/src/main/java/ch/zhaw/studyflow/services/persistence/CalendarDao.java
  backend/app/src/main/java/ch/zhaw/studyflow/services/persistence/DegreeDao.java
  backend/app/src/main/java/ch/zhaw/studyflow/services/persistence/memory/InMemoryDegreeDao.java
  backend/app/src/main/java/ch/zhaw/studyflow/utils/Validation.java
  backend/app/src/test/java/ch/zhaw/studyflow/controllers/DegreeControllerTest.java
  backend/app/src/test/java/ch/zhaw/studyflow/domain/curriculum/DegreeManagerImplTest.java
  backend/app/src/test/java/ch/zhaw/studyflow/webserver/sun/SunRootHttpHandlerTest.java
Labels: feature

#95 fix: added tests for semester and adjusted a few specifications
  backend/app/src/main/java/ch/zhaw/studyflow/Main.java
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/SemesterController.java
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/deo/SemesterDeo.java
  backend/app/src/test/java/ch/zhaw/studyflow/controllers/ModuleControllerTest.java
  backend/app/src/test/java/ch/zhaw/studyflow/controllers/SemesterControllerTest.java
Labels: test

#96 simple landing page
  client/package-lock.json
  client/package.json
  client/public/bg-pattern-register-section.webp
  client/public/hero.png
  client/public/icon.svg
  client/src/app/globals.css
  client/src/app/page.tsx
  client/src/components/global/gradient-wrapper.tsx
  client/src/components/global/layer-effect.tsx
  client/src/components/home/data.tsx
  client/src/components/home/faq-section.tsx
  client/src/components/home/feature-section.tsx
  client/src/components/home/footer.tsx
  client/src/components/home/hero-section.tsx
  client/src/components/home/navbar.tsx
  client/src/components/home/register-section.tsx
  client/src/components/home/testimonial-section.tsx
  client/src/components/icons/github.tsx
  client/src/components/icons/zhaw.tsx
Labels: feature

#97 fix json propery name
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/deo/Registration.java
Labels: bug

#100 98 feature connect backend to frontend
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/DegreeController.java
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/GradeController.java
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/ModuleController.java
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/SemesterController.java
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/StudentController.java
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/deo/ModuleDeo.java
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/deo/SemesterDeo.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/curriculum/Module.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/curriculum/Semester.java
  backend/app/src/main/java/ch/zhaw/studyflow/services/persistence/memory/InMemorySemesterDao.java
  backend/app/src/main/java/ch/zhaw/studyflow/services/persistence/sql/SQLModuleDao.java
  backend/app/src/main/java/ch/zhaw/studyflow/webserver/security/authentication/JwtBasedAuthenticationHandler.java
  backend/app/src/test/java/ch/zhaw/studyflow/controllers/ModuleControllerTest.java
  client/next.config.mjs
  client/src/app/api-old/_mockdata/appointments.ts
  client/src/app/api-old/_mockdata/calendars.ts
  client/src/app/api-old/_mockdata/degrees.ts
  client/src/app/api-old/_mockdata/grades.ts
  client/src/app/api-old/_mockdata/modules.ts
  client/src/app/api-old/_mockdata/semesters.ts
  client/src/app/api-old/_mockdata/user-token-settings.ts
  client/src/app/api-old/_utils.ts
  client/src/app/api-old/auth/login/route.ts
  client/src/app/api-old/auth/logout/route.ts
  client/src/app/api-old/auth/me/route.ts
  client/src/app/api-old/auth/register/route.ts
  client/src/app/api-old/auth/settings/route.ts
  client/src/app/api-old/calendars/[calendarId]/appointments/[appointmentId]/route.ts
  client/src/app/api-old/calendars/[calendarId]/appointments/route.ts
  client/src/app/api-old/calendars/[calendarId]/route.ts
  client/src/app/api-old/degrees/[degreeId]/ects/route.ts
  client/src/app/api-old/degrees/[degreeId]/grades/average/route.ts
  client/src/app/api-old/degrees/[degreeId]/grades/route.ts
  client/src/app/api-old/degrees/[degreeId]/route.ts
  client/src/app/api-old/degrees/route.ts
  client/src/app/api-old/modules/[modulesId]/route.ts
  client/src/app/api-old/modules/route.ts
  client/src/app/api-old/semesters/[semesterId]/route.ts
  client/src/app/api-old/semesters/route.ts
  client/src/components/dialogforms/module-form.tsx
  client/src/components/home/register-section.tsx
  client/src/components/sidebar/app-sidebar.tsx
  client/src/hooks/use-semester.ts
  client/src/hooks/use-user-settings.ts
  client/src/lib/api/auth/login.ts
  client/src/lib/api/auth/me.ts
  client/src/lib/api/auth/register.ts
  client/src/lib/api/auth/update-active-degree.ts
  client/src/lib/api/degrees/get-all-degrees.ts
  client/src/lib/api/degrees/new-degree.ts
  client/src/lib/api/degrees/update-degree.ts
  client/src/lib/api/modules/get-all-modules.ts
  client/src/lib/api/modules/new-module.ts
  client/src/lib/api/modules/update-module.ts
  client/src/lib/api/semesters/get-all-semesters.ts
  client/src/lib/api/semesters/new-semester.ts
  client/src/lib/tuam.ts
  client/src/middleware.ts
  docs/assets/excalidraw/architecture_and_visual_concept.excalidraw
Labels: feature

#99 use getAndIncrement instead of incrementAndGet
  backend/app/src/main/java/ch/zhaw/studyflow/services/persistence/memory/InMemoryModuleDao.java
  backend/app/src/test/java/ch/zhaw/studyflow/controllers/GradeControllerTest.java
Labels: bug

#104 FEATURE: implemented profile page form
  client/src/app/(main)/profile/page.tsx
  client/src/hooks/use-user-settings.ts
  client/src/lib/api/auth/logout.ts
  client/src/lib/api/auth/update-user.ts
  client/src/middleware.ts
Labels: feature

#107 [FEATURE]: Added logic to edit the semester.
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/SemesterController.java
  client/src/components/dialogforms/add-semester-form.tsx
  client/src/components/dialogforms/module-form.tsx
  client/src/components/dialogs/add-semester.tsx
  client/src/components/sidebar/app-sidebar.tsx
  client/src/lib/api/semesters/update-semester.ts
Labels: feature

#103 Feature/rework modules
  backend/app/src/main/java/ch/zhaw/studyflow/Main.java
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/ModuleController.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/student/Settings.java
  backend/app/src/test/java/ch/zhaw/studyflow/controllers/ModuleControllerTest.java
  backend/app/src/test/java/ch/zhaw/studyflow/controllers/StudentControllerTest.java
Labels: bug

#109 [FEATURE]: Added logic to edit and delete degrees
  client/src/app/(main)/degree/[degreeId]/page.tsx
Labels: feature

#111 Bugfix/routetrie
  backend/app/src/main/java/ch/zhaw/studyflow/webserver/controllers/routing/RouteTrie.java
  backend/app/src/main/java/ch/zhaw/studyflow/webserver/http/pipeline/InvokeByRequestContextEndpointInvoker.java
  backend/app/src/test/java/ch/zhaw/studyflow/webserver/controllers/routing/RouteTrieTest.java
  backend/app/src/test/java/ch/zhaw/studyflow/webserver/routing/RestRouteTest.java
  backend/app/src/test/java/ch/zhaw/studyflow/webserver/routing/RouteTrieTest.java
Labels: bug

#110 register grade controller
  backend/app/src/main/java/ch/zhaw/studyflow/Main.java
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/GradeController.java
Labels: bug

#114 rename api/calendar to api/calendars
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/CalendarController.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/student/Settings.java
Labels: bug

#113 Bugfix/cookie reset
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/StudentController.java
  backend/app/src/main/java/ch/zhaw/studyflow/webserver/controllers/routing/RouteTrie.java
  backend/app/src/main/java/ch/zhaw/studyflow/webserver/http/cookies/Cookie.java
  backend/app/src/main/java/ch/zhaw/studyflow/webserver/security/authentication/JwtBasedAuthenticationHandler.java
  backend/app/src/main/java/ch/zhaw/studyflow/webserver/security/principal/jwt/JwtPrincipalProvider.java
Labels: bug

#115 fix calendar dependency
  backend/app/src/main/java/ch/zhaw/studyflow/Main.java
Labels: bug

#125 Refactor student dao
  backend/app/src/main/java/ch/zhaw/studyflow/domain/student/impls/StudentManagerImpl.java
  backend/app/src/main/java/ch/zhaw/studyflow/services/persistence/SettingsDao.java
  backend/app/src/main/java/ch/zhaw/studyflow/services/persistence/memory/InMemorySettingsDao.java
  backend/app/src/test/java/ch/zhaw/studyflow/domain/student/StudentManagerTest.java
Labels: bug

#127 fix in memory dao
  backend/app/src/main/java/ch/zhaw/studyflow/services/persistence/memory/InMemorySettingsDao.java
Labels: bug

#133 130 feature fully implement grades in the frontend
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/GradeController.java
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/deo/ModuleGrade.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/curriculum/impls/SemesterManagerImpl.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/grade/impls/GradeManagerImpl.java
  backend/app/src/main/java/ch/zhaw/studyflow/services/persistence/GradeDao.java
  backend/app/src/main/java/ch/zhaw/studyflow/services/persistence/memory/InMemoryGradeDao.java
  backend/app/src/main/java/ch/zhaw/studyflow/services/persistence/sql/SQLGradeDao.java
  client/src/components/dialogforms/add-grade-form.tsx
  client/src/components/dialogs/add-grade.tsx
  client/src/components/global/grades-view.tsx
  client/src/hooks/use-grades.ts
  client/src/lib/api/degrees/get-grades-for-degree.ts
  client/src/lib/api/degrees/update-grades-for-module.ts
Labels: feature

#132 Adjustment of the updateByDegree:
  backend/app/src/main/java/ch/zhaw/studyflow/domain/curriculum/Semester.java
  backend/app/src/main/java/ch/zhaw/studyflow/services/persistence/memory/InMemoryGradeDao.java
  backend/app/src/test/java/ch/zhaw/studyflow/domain/grade/GradeManagerTest.java
  backend/app/src/test/java/ch/zhaw/studyflow/services/persistence/memory/InMemoryGradeDaoTest.java
Labels: refactor

#129 Add tests for Student updateSettings and getSettings
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/StudentController.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/curriculum/Degree.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/curriculum/impls/DegreeManagerImpl.java
  backend/app/src/main/resources/logging.properties
  backend/app/src/test/java/ch/zhaw/studyflow/controllers/StudentControllerTest.java
  backend/app/src/test/java/ch/zhaw/studyflow/domain/curriculum/DegreeManagerImplTest.java
Labels: feature

#135 Bugfix/semester calendar id not zero
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/SemesterController.java
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/deo/SemesterDeo.java
  backend/app/src/main/resources/logging.properties
Labels: bug

#136 Bugfix/degree manager id check
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/GradeController.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/curriculum/impls/DegreeManagerImpl.java
  backend/app/src/test/java/ch/zhaw/studyflow/controllers/GradeControllerTest.java
  backend/app/src/test/java/ch/zhaw/studyflow/domain/curriculum/DegreeManagerImplTest.java
Labels: feature, refactor, test

#140 Various cleanups
  backend/app/src/main/java/ch/zhaw/studyflow/Main.java
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/CalendarController.java
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/SemesterController.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/curriculum/impls/SemesterManagerImpl.java
  backend/app/src/main/java/ch/zhaw/studyflow/webserver/http/HttpMethod.java
  backend/app/src/main/java/ch/zhaw/studyflow/webserver/http/query/QueryParametersImpl.java
  backend/app/src/test/java/ch/zhaw/studyflow/controllers/SemesterControllerTest.java
Labels: refactor

#139 Always update models explicitly
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/SemesterController.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/curriculum/impls/DegreeManagerImpl.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/curriculum/impls/ModuleManagerImpl.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/curriculum/impls/SemesterManagerImpl.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/student/impls/StudentManagerImpl.java
Labels: refactor

#138 Add update appointment endpoint
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/CalendarController.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/calendar/impls/AppointmentManagerImpl.java
  backend/app/src/test/java/ch/zhaw/studyflow/controllers/CalendarControllerTest.java
  backend/app/src/test/java/ch/zhaw/studyflow/domain/appointment/AppointmentManagerTest.java
Labels: feature

#142 use correct variable
  backend/app/src/main/java/ch/zhaw/studyflow/domain/curriculum/impls/DegreeManagerImpl.java
Labels: bug

#143 Feature/update settings and degree on delete
  backend/app/src/main/java/ch/zhaw/studyflow/Main.java
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/DegreeController.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/curriculum/impls/DegreeManagerImpl.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/curriculum/impls/SemesterManagerImpl.java
  backend/app/src/test/java/ch/zhaw/studyflow/domain/curriculum/DegreeManagerImplTest.java
Labels: feature

#147 add cookie parsing tests and improve parsing
  backend/app/src/main/java/ch/zhaw/studyflow/webserver/http/cookies/Cookie.java
  backend/app/src/test/java/ch/zhaw/studyflow/webserver/http/cookies/CookieTest.java
Labels: refactor, test

#150 134 feature appointments onclick ondrag onresize events implementation in schedule page
  .github/workflows/client-test.yml
  client/src/app/(main)/schedule/page.tsx
  client/src/components/dashboard/daily-calendar-box.tsx
  client/src/components/dialogforms/appointment-form.tsx
  client/src/components/dialogforms/create-schedule-form.tsx
  client/src/components/dialogs/add-appointment.tsx
  client/src/components/dialogs/appointment-dialog.tsx
  client/src/components/dialogs/create-schedule.tsx
  client/src/components/sidebar/app-sidebar-header.tsx
  client/src/hooks/use-appointments.ts
  client/src/hooks/use-events.ts
  client/src/lib/api/calendar/get-appointments-for-calendar.ts
  client/src/lib/utils.ts
Labels: feature

#153 check if active semester = -1 on set.
  backend/app/src/main/java/ch/zhaw/studyflow/domain/curriculum/impls/DegreeManagerImpl.java
Labels: bug

#148 [FEATURE]: Added Dialogs for delete actions
  client/package-lock.json
  client/package.json
  client/src/app/(main)/degree/[degreeId]/page.tsx
  client/src/app/(main)/degree/[degreeId]/semester/[semesterId]/curriculum/page.tsx
  client/src/components/sidebar/app-sidebar.tsx
  client/src/components/ui/alert-dialog.tsx
Labels: feature

#154 rename handleIfUnauthenticated to handleRequest
  backend/app/src/main/java/ch/zhaw/studyflow/webserver/security/authentication/AuthenticationHandler.java
  backend/app/src/main/java/ch/zhaw/studyflow/webserver/security/authentication/JwtBasedAuthenticationHandler.java
  backend/app/src/test/java/ch/zhaw/studyflow/controllers/AuthMockHelpers.java
Labels: refactor

#152 Add Student tests and small refactor
  backend/app/src/main/java/ch/zhaw/studyflow/Main.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/student/Student.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/student/StudentManager.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/student/impls/StudentManagerImpl.java
  backend/app/src/test/java/ch/zhaw/studyflow/domain/curriculum/DegreeManagerImplTest.java
  backend/app/src/test/java/ch/zhaw/studyflow/domain/student/StudentManagerTest.java
  backend/app/src/test/java/ch/zhaw/studyflow/domain/studyplan/BasicModuleAllocationTest.java
Labels: refactor

#151 Unify dao naming
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/ModuleController.java
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/SemesterController.java
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/StudyplanController.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/calendar/impls/CalendarManagerImpl.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/curriculum/ModuleManager.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/curriculum/SemesterManager.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/curriculum/impls/DegreeManagerImpl.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/curriculum/impls/ModuleManagerImpl.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/curriculum/impls/SemesterManagerImpl.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/student/impls/StudentManagerImpl.java
  backend/app/src/main/java/ch/zhaw/studyflow/services/persistence/AppointmentDao.java
  backend/app/src/main/java/ch/zhaw/studyflow/services/persistence/CalendarDao.java
  backend/app/src/main/java/ch/zhaw/studyflow/services/persistence/DegreeDao.java
  backend/app/src/main/java/ch/zhaw/studyflow/services/persistence/GradeDao.java
  backend/app/src/main/java/ch/zhaw/studyflow/services/persistence/ModuleDao.java
  backend/app/src/main/java/ch/zhaw/studyflow/services/persistence/SemesterDao.java
  backend/app/src/main/java/ch/zhaw/studyflow/services/persistence/SettingsDao.java
  backend/app/src/main/java/ch/zhaw/studyflow/services/persistence/StudentDao.java
  backend/app/src/main/java/ch/zhaw/studyflow/services/persistence/memory/InMemoryAppointmentDao.java
  backend/app/src/main/java/ch/zhaw/studyflow/services/persistence/memory/InMemoryCalendarDao.java
  backend/app/src/main/java/ch/zhaw/studyflow/services/persistence/memory/InMemoryDegreeDao.java
  backend/app/src/main/java/ch/zhaw/studyflow/services/persistence/memory/InMemoryModuleDao.java
  backend/app/src/main/java/ch/zhaw/studyflow/services/persistence/memory/InMemorySemesterDao.java
  backend/app/src/main/java/ch/zhaw/studyflow/services/persistence/memory/InMemorySettingsDao.java
  backend/app/src/main/java/ch/zhaw/studyflow/services/persistence/memory/InMemoryStudentDao.java
  backend/app/src/main/java/ch/zhaw/studyflow/services/persistence/sql/SQLAppointmentDao.java
  backend/app/src/main/java/ch/zhaw/studyflow/services/persistence/sql/SQLCalendarDao.java
  backend/app/src/test/java/ch/zhaw/studyflow/controllers/ModuleControllerTest.java
  backend/app/src/test/java/ch/zhaw/studyflow/controllers/SemesterControllerTest.java
  backend/app/src/test/java/ch/zhaw/studyflow/domain/student/StudentManagerTest.java
Labels: refactor

#156 Fix delete semester
  backend/app/src/main/java/ch/zhaw/studyflow/domain/curriculum/impls/SemesterManagerImpl.java
Labels: bug

#158 test for duplicate email on student update
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/StudentController.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/student/impls/StudentManagerImpl.java
  backend/app/src/test/java/ch/zhaw/studyflow/domain/student/StudentManagerTest.java
Labels: bug

#160 fix degree average
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/GradeController.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/curriculum/DegreeManager.java
  backend/app/src/main/java/ch/zhaw/studyflow/services/persistence/GradeDao.java
  backend/app/src/test/java/ch/zhaw/studyflow/controllers/GradeControllerTest.java
Labels: bug

#162 Fix SQLModuleDao
  backend/app/src/main/java/ch/zhaw/studyflow/services/persistence/sql/SQLModuleDao.java
Labels: bug, refactor

#161 REFACTOR: refactored client
  client/src/app/(auth)/login/page.tsx
  client/src/app/(auth)/register/page.tsx
  client/src/app/(main)/degree/[degreeId]/page.tsx
  client/src/app/(main)/degree/[degreeId]/semester/[semesterId]/curriculum/page.tsx
  client/src/app/(main)/profile/page.tsx
  client/src/app/(main)/schedule/page.tsx
  client/src/components/dashboard/grade-box.tsx
  client/src/components/dialogforms/add-grade-form.tsx
  client/src/components/dialogforms/add-semester-form.tsx
  client/src/components/dialogforms/create-schedule-form.tsx
  client/src/components/dialogforms/module-form.tsx
  client/src/components/dialogs/add-semester.tsx
  client/src/components/dialogs/module-dialog.tsx
  client/src/components/global/grades-view.tsx
  client/src/components/home/register-section.tsx
  client/src/components/sidebar/app-sidebar.tsx
  client/src/components/sidebar/user-dropdown.tsx
  client/src/hooks/use-appointments.ts
  client/src/hooks/use-average.ts
  client/src/hooks/use-degree.ts
  client/src/hooks/use-grades.ts
  client/src/hooks/use-modules.ts
  client/src/hooks/use-semester.ts
  client/src/hooks/use-user-settings.ts
  client/src/lib/api/calendar/get-appointments-for-calendar.ts
  client/src/lib/api/degrees/update-grades-for-module.ts
  client/src/lib/api/modules/get-all-modules.ts
  client/src/lib/api/semesters/get-all-semesters.ts
  client/src/lib/tuam.ts
Labels: refactor

#163 SemesterManagerTests
  backend/app/src/main/java/ch/zhaw/studyflow/domain/curriculum/Module.java
  backend/app/src/test/java/ch/zhaw/studyflow/domain/calendar/SemesterManagerTest.java
Labels: feature

#165 Javadoc
  backend/app/build.gradle.kts
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/DegreeController.java
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/SemesterController.java
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/StudentController.java
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/StudyplanController.java
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/deo/LoginRequest.java
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/deo/MeResponse.java
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/deo/ModuleDeo.java
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/deo/ModuleGrade.java
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/deo/Registration.java
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/deo/SemesterDeo.java
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/deo/SemesterGrade.java
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/deo/StudentDeo.java
  backend/app/src/main/java/ch/zhaw/studyflow/controllers/deo/StudyplanParameters.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/curriculum/Degree.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/curriculum/DegreeManager.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/curriculum/Module.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/curriculum/ModuleManager.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/curriculum/SemesterManager.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/curriculum/impls/SemesterManagerImpl.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/grade/Grade.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/student/Settings.java
  backend/app/src/main/java/ch/zhaw/studyflow/domain/student/Student.java
  backend/app/src/main/java/ch/zhaw/studyflow/services/MapServiceCollection.java
  backend/app/src/main/java/ch/zhaw/studyflow/services/MapServiceCollectionBuilder.java
  backend/app/src/main/java/ch/zhaw/studyflow/services/ServiceCollection.java
  backend/app/src/main/java/ch/zhaw/studyflow/utils/Result.java
  backend/app/src/main/java/ch/zhaw/studyflow/utils/Validation.java
  backend/app/src/main/java/ch/zhaw/studyflow/webserver/WebServer.java
  backend/app/src/main/java/ch/zhaw/studyflow/webserver/WebServerBuilder.java
  backend/app/src/main/java/ch/zhaw/studyflow/webserver/controllers/routing/RestRoute.java
  backend/app/src/main/java/ch/zhaw/studyflow/webserver/controllers/routing/RouteSegment.java
  backend/app/src/main/java/ch/zhaw/studyflow/webserver/controllers/routing/RouteTrie.java
  backend/app/src/main/java/ch/zhaw/studyflow/webserver/controllers/routing/SegmentType.java
  backend/app/src/main/java/ch/zhaw/studyflow/webserver/http/HttpMethod.java
  backend/app/src/main/java/ch/zhaw/studyflow/webserver/http/HttpStatusCode.java
  backend/app/src/main/java/ch/zhaw/studyflow/webserver/http/MapCaptureContainer.java
  backend/app/src/main/java/ch/zhaw/studyflow/webserver/http/contents/JsonContent.java
  backend/app/src/main/java/ch/zhaw/studyflow/webserver/http/contents/MapReadableBodyContentFactory.java
  backend/app/src/main/java/ch/zhaw/studyflow/webserver/http/contents/TextContent.java
  backend/app/src/main/java/ch/zhaw/studyflow/webserver/http/pipeline/PipelineBuilder.java
  backend/app/src/main/java/ch/zhaw/studyflow/webserver/http/query/QueryParameters.java
  backend/app/src/main/java/ch/zhaw/studyflow/webserver/http/query/QueryParametersImpl.java
  backend/app/src/main/java/ch/zhaw/studyflow/webserver/security/principal/Principal.java
  backend/app/src/main/java/ch/zhaw/studyflow/webserver/security/principal/PrincipalProvider.java
  backend/app/src/main/java/ch/zhaw/studyflow/webserver/security/principal/impls/PrincipalImpl.java
  backend/app/src/main/java/ch/zhaw/studyflow/webserver/security/principal/jwt/JwtHashAlgorithm.java
  backend/app/src/main/java/ch/zhaw/studyflow/webserver/sun/SunHttpRequest.java
  backend/app/src/main/java/ch/zhaw/studyflow/webserver/sun/SunHttpRequestContext.java
  backend/app/src/main/java/ch/zhaw/studyflow/webserver/sun/SunHttpResponse.java
  backend/app/src/main/java/ch/zhaw/studyflow/webserver/sun/SunHttpServerWebServer.java
  backend/app/src/main/java/ch/zhaw/studyflow/webserver/sun/SunHttpServerWebServerBuilder.java
Labels: refactor
